// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMK-8UoaJ-HEJ6A-k5HOQYoaDWzA-RN_c',
    appId: '1:904700957731:web:6c7c7ad527b71531974d96',
    messagingSenderId: '904700957731',
    projectId: 'fastag-a406a',
    authDomain: 'fastag-a406a.firebaseapp.com',
    storageBucket: 'fastag-a406a.appspot.com',
    measurementId: 'G-QYV3E917X9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQi5869hri8fvdioFa3ylE0pLJXTxfJ9w',
    appId: '1:904700957731:android:e1371464d9313a96974d96',
    messagingSenderId: '904700957731',
    projectId: 'fastag-a406a',
    storageBucket: 'fastag-a406a.appspot.com',
  );
}
